project: 
  type: website
  output-dir: docs

website: 
  title: Wstęp do kwantowego uczenia maszynowego
  sidebar:
    style: "docked" 
    contents:
      - index.qmd
      - section : "Wykłady"
        contents:
          - lectures/wyklad1.qmd
          - lectures/wyklad2.qmd
          - lectures/wyklad3.qmd
          - lectures/wyklad4.qmd
      - section: "Ćwiczenia"
        contents:
          - cwiczenia/cw1.ipynb
          - cwiczenia/cw2.ipynb
          - cwiczenia/cw3.ipynb
          - cwiczenia/cw4.ipynb
          - cwiczenia/cw5.ipynb
          - cwiczenia/ml.ipynb
          - cwiczenia/titanic.ipynb
  navbar:
    left:
          - href: sylabus.qmd
            text: Sylabus
          - href: ksiazki.qmd
            text: Książki
          

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    self-contained-math: true